"""phase7 extraction review and verified domain records

Revision ID: 0460f961aa05
Revises: 79e46a4c8ad4
Create Date: 2026-07-14 06:54:43.528150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0460f961aa05'
down_revision: Union[str, None] = '79e46a4c8ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interest_income',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filing_session_id', sa.Uuid(), nullable=False),
    sa.Column('tax_document_id', sa.Uuid(), nullable=False),
    sa.Column('document_extraction_id', sa.Uuid(), nullable=False),
    sa.Column('interest_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('interest_amount IS NULL OR interest_amount >= 0', name='ck_interest_income_amount_non_negative'),
    sa.ForeignKeyConstraint(['document_extraction_id'], ['document_extractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filing_session_id'], ['filing_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_document_id'], ['tax_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_extraction_id', name='uq_interest_income_extraction')
    )
    op.create_table('salary_income',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filing_session_id', sa.Uuid(), nullable=False),
    sa.Column('tax_document_id', sa.Uuid(), nullable=False),
    sa.Column('document_extraction_id', sa.Uuid(), nullable=False),
    sa.Column('employer_name', sa.String(length=255), nullable=True),
    sa.Column('gross_salary', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tds_deducted', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('gross_salary IS NULL OR gross_salary >= 0', name='ck_salary_income_gross_salary_non_negative'),
    sa.CheckConstraint('tds_deducted IS NULL OR tds_deducted >= 0', name='ck_salary_income_tds_deducted_non_negative'),
    sa.ForeignKeyConstraint(['document_extraction_id'], ['document_extractions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['filing_session_id'], ['filing_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_document_id'], ['tax_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_extraction_id', name='uq_salary_income_extraction')
    )
    op.create_table('extracted_field_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('extracted_field_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('CONFIRM', 'CORRECT', name='verification_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('verified_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['extracted_field_id'], ['extracted_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['extracted_field_verifications.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_extracted_field_verifications_current', 'extracted_field_verifications', ['extracted_field_id'], unique=True, postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current'))
    op.add_column('document_processing_jobs', sa.Column('error_code', sa.Enum('STORAGE_OBJECT_MISSING', 'STORAGE_ERROR', 'PROVIDER_ERROR', 'UNKNOWN_ERROR', name='extraction_failure_code', native_enum=False, create_constraint=True), nullable=True))
    op.add_column('document_processing_jobs', sa.Column('error_detail', sa.Text(), nullable=True))
    op.drop_column('document_processing_jobs', 'error_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_processing_jobs', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('document_processing_jobs', 'error_detail')
    op.drop_column('document_processing_jobs', 'error_code')
    op.drop_index('uq_extracted_field_verifications_current', table_name='extracted_field_verifications', postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current'))
    op.drop_table('extracted_field_verifications')
    op.drop_table('salary_income')
    op.drop_table('interest_income')
    # ### end Alembic commands ###
