"""phase3 questionnaire engine

Revision ID: 1a23455ce2e7
Revises: 84ce6fd8fdf0
Create Date: 2026-07-14 00:25:30.783855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a23455ce2e7'
down_revision: Union[str, None] = '84ce6fd8fdf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_year', sa.String(length=9), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='questionnaire_version_status', native_enum=False, create_constraint=True), server_default='DRAFT', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_year', 'version_number', name='uq_questionnaire_version_ay_num')
    )
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('questionnaire_version_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.Enum('SINGLE_CHOICE', 'MULTI_CHOICE', 'BOOLEAN', 'CURRENCY', 'NUMBER', 'DATE', 'TEXT', 'DOCUMENT_UPLOAD', 'INFORMATION', 'REVIEW_CARD', name='question_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['questionnaire_version_id'], ['questionnaire_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('questionnaire_version_id', 'key', name='uq_questions_version_key'),
    sa.UniqueConstraint('questionnaire_version_id', 'order_index', name='uq_questions_version_order')
    )
    op.create_table('question_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filing_session_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('questionnaire_version_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_session_id'], ['filing_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['questionnaire_version_id'], ['questionnaire_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['question_answers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_question_answers_current', 'question_answers', ['filing_session_id', 'question_id'], unique=True, postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current'))
    op.create_table('question_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('questionnaire_version_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['questionnaire_version_id'], ['questionnaire_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'value', name='uq_question_options_question_value')
    )
    op.create_table('question_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('questionnaire_version_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('condition_operator', sa.Enum('ALWAYS', 'EQUALS', 'NOT_EQUALS', 'IN', name='rule_condition_operator', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('condition_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('action', sa.Enum('SHOW_QUESTION', 'SKIP_QUESTION', 'GO_TO_QUESTION', 'SET_PROFILE_FLAG', 'SET_COMPLEXITY', 'REQUIRE_REVIEW', 'END_FLOW', name='rule_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('target_question_id', sa.Uuid(), nullable=True),
    sa.Column('action_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['questionnaire_version_id'], ['questionnaire_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # batch_alter_table: SQLite can't ALTER TABLE ADD CONSTRAINT directly and
    # needs the copy-and-move strategy; batch mode also works fine on Postgres.
    with op.batch_alter_table('filing_sessions') as batch_op:
        batch_op.add_column(sa.Column('questionnaire_version_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            'filing_sessions_questionnaire_version_id_fkey',
            'questionnaire_versions',
            ['questionnaire_version_id'],
            ['id'],
            ondelete='RESTRICT',
        )
    # ### end Alembic commands ###

    if op.get_bind().dialect.name == "postgresql":
        _create_immutability_triggers()


def _create_immutability_triggers() -> None:
    """Published questionnaire versions (and their questions/options/rules) must
    not be silently modified — enforced here at the database level, not only in
    application code. PostgreSQL-only (the SQLite test path relies on the
    service-layer guard instead — see app/engines/questionnaire/lifecycle.py).
    """
    op.execute(
        """
        CREATE OR REPLACE FUNCTION fn_reject_change_to_published_questionnaire_version()
        RETURNS trigger AS $$
        BEGIN
            IF OLD.status = 'PUBLISHED' THEN
                RAISE EXCEPTION 'questionnaire_versions: published version % is immutable', OLD.id;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_questionnaire_versions_immutable
        BEFORE UPDATE ON questionnaire_versions
        FOR EACH ROW EXECUTE FUNCTION fn_reject_change_to_published_questionnaire_version();
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION fn_reject_child_change_if_version_published()
        RETURNS trigger AS $$
        DECLARE
            v_status text;
            v_version_id uuid;
        BEGIN
            v_version_id := COALESCE(NEW.questionnaire_version_id, OLD.questionnaire_version_id);
            SELECT status INTO v_status FROM questionnaire_versions WHERE id = v_version_id;
            IF v_status = 'PUBLISHED' THEN
                RAISE EXCEPTION 'questionnaire_versions: cannot modify children of published version %', v_version_id;
            END IF;
            RETURN COALESCE(NEW, OLD);
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table_name in ("questions", "question_options", "question_rules"):
        op.execute(
            f"""
            CREATE TRIGGER trg_{table_name}_immutable
            BEFORE INSERT OR UPDATE OR DELETE ON {table_name}
            FOR EACH ROW EXECUTE FUNCTION fn_reject_child_change_if_version_published();
            """
        )


def _drop_immutability_triggers() -> None:
    for table_name in ("questions", "question_options", "question_rules"):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table_name}_immutable ON {table_name};")
    op.execute("DROP FUNCTION IF EXISTS fn_reject_child_change_if_version_published();")
    op.execute("DROP TRIGGER IF EXISTS trg_questionnaire_versions_immutable ON questionnaire_versions;")
    op.execute("DROP FUNCTION IF EXISTS fn_reject_change_to_published_questionnaire_version();")


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        _drop_immutability_triggers()

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filing_sessions') as batch_op:
        batch_op.drop_constraint('filing_sessions_questionnaire_version_id_fkey', type_='foreignkey')
        batch_op.drop_column('questionnaire_version_id')
    op.drop_table('question_rules')
    op.drop_table('question_options')
    op.drop_index('uq_question_answers_current', table_name='question_answers', postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current'))
    op.drop_table('question_answers')
    op.drop_table('questions')
    op.drop_table('questionnaire_versions')
    # ### end Alembic commands ###
