"""phase10 consent and audit

Revision ID: 396224f6248c
Revises: 90595e839520
Create Date: 2026-07-18 08:55:40.098733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '396224f6248c'
down_revision: Union[str, None] = '90595e839520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='consent_definition_status', native_enum=False, create_constraint=True), server_default='DRAFT', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version_number', name='uq_consent_definitions_code_version')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_code', sa.Enum('FILING_SESSION_CREATED', 'QUESTION_ANSWER_CREATED', 'QUESTION_ANSWER_CHANGED', 'FILING_FLAG_ACTIVATED', 'FILING_FLAG_DEACTIVATED', 'DOCUMENT_UPLOADED', 'DOCUMENT_DELETED', 'EXTRACTION_STARTED', 'EXTRACTION_COMPLETED', 'EXTRACTION_FAILED', 'EXTRACTED_FIELD_CONFIRMED', 'EXTRACTED_FIELD_CORRECTED', 'DEDUCTION_CLAIMED', 'DEDUCTION_CHANGED', 'TAX_CALCULATION_CREATED', 'TAX_CALCULATION_RECALCULATED', 'CONSENT_ACCEPTED', 'CONSENT_WITHDRAWN', name='audit_event_code', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('actor_type', sa.Enum('USER', 'SYSTEM', name='actor_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('filing_session_id', sa.Uuid(), nullable=True),
    sa.Column('subject_type', sa.String(length=50), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('event_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['filing_session_id'], ['filing_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_filing_session_created', 'audit_logs', ['filing_session_id', 'created_at'], unique=False)
    op.create_table('user_consents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('filing_session_id', sa.Uuid(), nullable=True),
    sa.Column('consent_definition_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACCEPTED', 'WITHDRAWN', name='user_consent_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consent_definition_id'], ['consent_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['filing_session_id'], ['filing_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['user_consents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_user_consents_current', 'user_consents', ['user_id', 'filing_session_id', 'consent_definition_id'], unique=True, postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current'))
    # ### end Alembic commands ###

    if op.get_bind().dialect.name == "postgresql":
        _create_immutability_triggers()


def _create_immutability_triggers() -> None:
    """Two independent PostgreSQL-level protections, mirroring the existing
    questionnaire_versions/tax_rule_sets trigger pattern (the SQLite test
    path relies on the service-layer guards instead — app/repositories/
    audit_log.py exposes no update/delete function at all, and
    app/repositories/consent.py never updates a PUBLISHED consent_definition):

    1. audit_logs is fully append-only — EVERY row is protected, not just
       "published" ones (there's no draft/published lifecycle for audit
       events), so both UPDATE and DELETE are rejected unconditionally.
    2. consent_definitions follows the DRAFT->PUBLISHED versioning pattern
       exactly like questionnaire_versions/tax_rule_sets: a DRAFT row may
       still be edited before publish, but a PUBLISHED row is immutable.
    """
    op.execute(
        """
        CREATE OR REPLACE FUNCTION fn_reject_audit_log_mutation()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_logs: rows are append-only and cannot be updated or deleted';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_audit_logs_append_only
        BEFORE UPDATE OR DELETE ON audit_logs
        FOR EACH ROW EXECUTE FUNCTION fn_reject_audit_log_mutation();
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION fn_reject_change_to_published_consent_definition()
        RETURNS trigger AS $$
        BEGIN
            IF OLD.status = 'PUBLISHED' THEN
                RAISE EXCEPTION 'consent_definitions: published definition % is immutable', OLD.id;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_consent_definitions_immutable
        BEFORE UPDATE ON consent_definitions
        FOR EACH ROW EXECUTE FUNCTION fn_reject_change_to_published_consent_definition();
        """
    )


def _drop_immutability_triggers() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_consent_definitions_immutable ON consent_definitions;")
    op.execute("DROP FUNCTION IF EXISTS fn_reject_change_to_published_consent_definition();")
    op.execute("DROP TRIGGER IF EXISTS trg_audit_logs_append_only ON audit_logs;")
    op.execute("DROP FUNCTION IF EXISTS fn_reject_audit_log_mutation();")


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        _drop_immutability_triggers()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_consents_current', table_name='user_consents', postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current'))
    op.drop_table('user_consents')
    op.drop_index('ix_audit_logs_filing_session_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('consent_definitions')
    # ### end Alembic commands ###
