"""phase5 tax documents

Revision ID: 39b2b0ccc952
Revises: bb42c2a419d1
Create Date: 2026-07-14 01:18:47.249886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39b2b0ccc952'
down_revision: Union[str, None] = 'bb42c2a419d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filing_session_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('storage_provider', sa.Enum('LOCAL_FILESYSTEM', name='storage_provider_name', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'DELETED', name='document_status', native_enum=False, create_constraint=True), server_default='UPLOADED', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes > 0', name='ck_tax_documents_size_positive'),
    sa.ForeignKeyConstraint(['filing_session_id'], ['filing_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key', name='uq_tax_documents_storage_key')
    )
    op.create_index('uq_tax_documents_session_hash_active', 'tax_documents', ['filing_session_id', 'content_hash'], unique=True, postgresql_where=sa.text("status = 'UPLOADED'"), sqlite_where=sa.text("status = 'UPLOADED'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_tax_documents_session_hash_active', table_name='tax_documents', postgresql_where=sa.text("status = 'UPLOADED'"), sqlite_where=sa.text("status = 'UPLOADED'"))
    op.drop_table('tax_documents')
    # ### end Alembic commands ###
