"""phase6 async extraction pipeline

Revision ID: 79e46a4c8ad4
Revises: 39b2b0ccc952
Create Date: 2026-07-14 06:30:32.296608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79e46a4c8ad4'
down_revision: Union[str, None] = '39b2b0ccc952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_processing_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tax_document_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('MOCK', name='extraction_provider_name', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='document_processing_job_status', native_enum=False, create_constraint=True), server_default='PENDING', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tax_document_id'], ['tax_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_extractions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_processing_job_id', sa.Uuid(), nullable=False),
    sa.Column('tax_document_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('MOCK', name='extraction_provider_name', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('provider_version', sa.String(length=50), nullable=False),
    sa.Column('raw_output', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_processing_job_id'], ['document_processing_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tax_document_id'], ['tax_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_processing_job_id', name='uq_document_extractions_job')
    )
    op.create_table('extracted_fields',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_extraction_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('raw_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_extracted_fields_confidence_range'),
    sa.ForeignKeyConstraint(['document_extraction_id'], ['document_extractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extracted_fields')
    op.drop_table('document_extractions')
    op.drop_table('document_processing_jobs')
    # ### end Alembic commands ###
