"""phase9 tax calculation engine

Revision ID: 90595e839520
Revises: c2c83f9d8b3b
Create Date: 2026-07-14 08:56:45.414112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90595e839520'
down_revision: Union[str, None] = 'c2c83f9d8b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deductions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filing_session_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('claimed_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('claimed_amount >= 0', name='ck_deductions_claimed_amount_non_negative'),
    sa.ForeignKeyConstraint(['filing_session_id'], ['filing_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_session_id', 'code', name='uq_deductions_session_code')
    )
    op.create_table('tax_calculations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filing_session_id', sa.Uuid(), nullable=False),
    sa.Column('tax_rule_set_id', sa.Uuid(), nullable=False),
    sa.Column('regime', sa.Enum('OLD', 'NEW', name='tax_regime', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('calculation_engine_version', sa.String(length=20), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('gross_total_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_deductions_applied', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxable_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_before_rebate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rebate_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_after_rebate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cess_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_tax_liability', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_tds_credit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_payable', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cess_amount >= 0', name='ck_tax_calculations_cess_non_negative'),
    sa.CheckConstraint('gross_total_income >= 0', name='ck_tax_calculations_gti_non_negative'),
    sa.CheckConstraint('rebate_amount >= 0', name='ck_tax_calculations_rebate_non_negative'),
    sa.CheckConstraint('tax_after_rebate >= 0', name='ck_tax_calculations_tax_after_rebate_non_negative'),
    sa.CheckConstraint('tax_before_rebate >= 0', name='ck_tax_calculations_tax_before_rebate_non_negative'),
    sa.CheckConstraint('taxable_income >= 0', name='ck_tax_calculations_taxable_income_non_negative'),
    sa.CheckConstraint('total_deductions_applied >= 0', name='ck_tax_calculations_deductions_non_negative'),
    sa.CheckConstraint('total_tax_liability >= 0', name='ck_tax_calculations_total_tax_liability_non_negative'),
    sa.CheckConstraint('total_tds_credit >= 0', name='ck_tax_calculations_tds_credit_non_negative'),
    sa.ForeignKeyConstraint(['filing_session_id'], ['filing_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['tax_calculations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tax_rule_set_id'], ['tax_rule_sets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_tax_calculations_current', 'tax_calculations', ['filing_session_id', 'regime'], unique=True, postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current'))
    op.create_table('calculation_line_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tax_calculation_id', sa.Uuid(), nullable=False),
    sa.Column('step_code', sa.String(length=60), nullable=False),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('step_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tax_calculation_id'], ['tax_calculations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_calculation_id', 'sequence_index', name='uq_calc_line_items_calc_sequence')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculation_line_items')
    op.drop_index('uq_tax_calculations_current', table_name='tax_calculations', postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current'))
    op.drop_table('tax_calculations')
    op.drop_table('deductions')
    # ### end Alembic commands ###
