"""phase4 decision engine filing flags

Revision ID: bb42c2a419d1
Revises: 1a23455ce2e7
Create Date: 2026-07-14 00:51:11.282079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb42c2a419d1'
down_revision: Union[str, None] = '1a23455ce2e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filing_flags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filing_session_id', sa.Uuid(), nullable=False),
    sa.Column('flag_code', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_session_id'], ['filing_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_session_id', 'flag_code', name='uq_filing_flags_session_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filing_flags')
    # ### end Alembic commands ###
