"""phase8 tax rule sets and supported case validator

Revision ID: c2c83f9d8b3b
Revises: 0460f961aa05
Create Date: 2026-07-14 08:17:07.993426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2c83f9d8b3b'
down_revision: Union[str, None] = '0460f961aa05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_rule_sets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_year', sa.String(length=9), nullable=False),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='tax_rule_set_status', native_enum=False, create_constraint=True), server_default='DRAFT', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_year', 'engine_version', name='uq_tax_rule_sets_ay_engine_version')
    )
    op.create_table('tax_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tax_rule_set_id', sa.Uuid(), nullable=False),
    sa.Column('regime', sa.Enum('OLD', 'NEW', name='tax_regime', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('rule_type', sa.Enum('SLAB', 'REBATE', 'SURCHARGE', 'CESS', 'DEDUCTION', name='tax_rule_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tax_rule_set_id'], ['tax_rule_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_rule_set_id', 'regime', 'code', name='uq_tax_rules_set_regime_code')
    )
    # ### end Alembic commands ###

    if op.get_bind().dialect.name == "postgresql":
        _create_immutability_triggers()


def _create_immutability_triggers() -> None:
    """Published tax rule sets (and their tax_rules) must not be silently
    modified — enforced here at the database level, not only in application
    code (CLAUDE.md: "Tax/questionnaire rule versions, once published, are
    immutable"). PostgreSQL-only (the SQLite test path relies on the
    service-layer guard instead — see app/engines/tax/lifecycle.py). Mirrors
    the Phase 3 questionnaire_versions trigger pattern exactly.
    """
    op.execute(
        """
        CREATE OR REPLACE FUNCTION fn_reject_change_to_published_tax_rule_set()
        RETURNS trigger AS $$
        BEGIN
            IF OLD.status = 'PUBLISHED' THEN
                RAISE EXCEPTION 'tax_rule_sets: published rule set % is immutable', OLD.id;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_tax_rule_sets_immutable
        BEFORE UPDATE ON tax_rule_sets
        FOR EACH ROW EXECUTE FUNCTION fn_reject_change_to_published_tax_rule_set();
        """
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION fn_reject_tax_rule_change_if_set_published()
        RETURNS trigger AS $$
        DECLARE
            v_status text;
            v_rule_set_id uuid;
        BEGIN
            v_rule_set_id := COALESCE(NEW.tax_rule_set_id, OLD.tax_rule_set_id);
            SELECT status INTO v_status FROM tax_rule_sets WHERE id = v_rule_set_id;
            IF v_status = 'PUBLISHED' THEN
                RAISE EXCEPTION 'tax_rule_sets: cannot modify rules of published rule set %', v_rule_set_id;
            END IF;
            RETURN COALESCE(NEW, OLD);
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_tax_rules_immutable
        BEFORE INSERT OR UPDATE OR DELETE ON tax_rules
        FOR EACH ROW EXECUTE FUNCTION fn_reject_tax_rule_change_if_set_published();
        """
    )


def _drop_immutability_triggers() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_tax_rules_immutable ON tax_rules;")
    op.execute("DROP FUNCTION IF EXISTS fn_reject_tax_rule_change_if_set_published();")
    op.execute("DROP TRIGGER IF EXISTS trg_tax_rule_sets_immutable ON tax_rule_sets;")
    op.execute("DROP FUNCTION IF EXISTS fn_reject_change_to_published_tax_rule_set();")


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        _drop_immutability_triggers()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_rules')
    op.drop_table('tax_rule_sets')
    # ### end Alembic commands ###
